name: Build and Push FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image with SHA tag
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/fastapi-devops-app:${{ github.sha }} \
            --push .
