name: Build and Push FastAPI App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Build and Push Job
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: fastapi-devops-app
      DOCKER_REGISTRY: docker.io/${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: get_sha
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./fastapi-app/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_sha.outputs.VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
